### ISSUE TITLE
Cannot run, raises "undefined is not function" error

### ISSUE THREAD

**Issue by diki** [golbin/git-commander#18]
I installed it globally on node v0.10.26. When i tried to run it an error occurs with this stack;
TypeError: undefined is not a function
    at Git.status (/usr/local/lib/node_modules/git-commander/model/git.js:70:16)
    at Object.main.reload (/usr/local/lib/node_modules/git-commander/controller/main.js:94:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/git-commander/bin/git-commander:3:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by diki** [comment]
It started to work with the latest update of nodejs v0.12.7.

**Comment by gumpcha** [comment]
child_process.execSync is [only available for node v0.12](https://strongloop.com/strongblog/whats-new-in-node-js-v0-12-execsync-a-synchronous-api-for-child-processes/).

```
    execSync = require('child_process').execSync;
```

It looks like there is [3 options to fix](http://stackoverflow.com/questions/25320047/synchronous-child-process-calls-for-shell-scripting-including-cli-in-node-js-0) this issue for node v0.10.
- [`shelljs`](https://www.npmjs.com/package/shelljs)
- [`execSync`](https://www.npmjs.com/package/execSync)
- [`execsync`](https://www.npmjs.com/package/execsync)

What's your choice? @golbin :)

**Comment by golbin** [comment]
@diki @gumpcha Thanks! And I'll just add engines options for proper node versions instead of code patches. :-)
